### ISSUE TITLE
There should be some modifies apply to the database

### ISSUE THREAD

**Issue by MuYouTu** [addb-swstarlab/LEAST_Redis#1]
@addb-swstarlab @hshs1103 

It has been confirmed that the data recovery in the radis database No.0 works normally.
However the recover couldn't apply to the database above No.1.
So there should be some suitable modifies also apply to the databae above No.1.

**Comment by addb-swstarlab** [comment]
@MuYouTu 
Thanks for the comments. We will modify the module after functional review.

@rlagnlrns 
Please process the case after functional review.

**Comment by addb-swstarlab** [comment]
The processing of the issue mentioned by @Mutuyou has been completed.

Please check the link below.
https://github.com/addb-swstarlab/LEAST_Redis/tree/master
