### ISSUE TITLE
Add comments on LEAST logging operation(aof_with_rdb) and recovery operation(loadDataFromDisk)

### ISSUE THREAD

**Issue by Magichka1031** [addb-swstarlab/LEAST_Redis#2]
In the case of LEAST, i confirmed through README.md that it is a version that utilizes data parallelism in LESS.

However, it is difficult to understand the code because there is no additional explanation.

Please add a description of the aof_with_rdb that performs the logging operation and the loadDataFromDisk function that performs the recovery operation.

**Comment by hshs1103** [comment]
Hello @Magichka1031 , Thanks for your question. 

We will reflect on your request ASAP.

p.s. To help you understand more in detail, I attach some pictures of LEAST Logging operation.

![least1](https://user-images.githubusercontent.com/20452176/93846809-1695a080-fce0-11ea-951d-8eb4fbf2d357.png)

![least2](https://user-images.githubusercontent.com/20452176/93846815-1a292780-fce0-11ea-943c-ed918c7a136d.png)

![least3](https://user-images.githubusercontent.com/20452176/93846818-1d241800-fce0-11ea-9bfb-5e1556b6bf02.png)

![least4](https://user-images.githubusercontent.com/20452176/93846949-7f7d1880-fce0-11ea-9703-df3fea08f38d.png)

![least5](https://user-images.githubusercontent.com/20452176/93846827-21e8cc00-fce0-11ea-9d84-f9c9e11dcc4e.png)


If you have any additional questions, please leave a comment.

**Comment by hshs1103** [comment]
Hello @Magichka1031 .

Developers(@dkdl012 and @rlagnlrns ) of our project have added a description of LEAST from logging to recovery.

You can check the added part by looking at the latest code of the master branch.

If you have additional questions, please register a new issue.
